### PR TITLE
fix: improve file size limit feedback with adaptive KB/MB units

### LINKED ISSUE #274: Improve file size limit feedback
Currently, if a file is too large, the error might not be clear. Add a per-extension size recommendation and a friendly error message distinguishing "file too large" from "format unsupported".

Scope: FileContentExtractor.kt + UI error display in ChatInputField

### PR DESCRIPTION
**Pull request by miguel-baptista07**
Fixes #274

## Problem
The file size error message was always showing "0.0MB" for small files because the calculation always divided by 1024×1024, giving a result less than 1 for small files.

## Changes
- Added adaptive units: shows KB when file is smaller than 1MB, MB otherwise
- Fixed secondary bug dividing by 1000×1000 instead of 1024×1024 in FileSizeExceededException
- Applied fix in 4 locations: ChatInputField.kt, ErrorHandler.kt (×2) and FileContentExtractor.kt

## Before
File 'file_teste.txt' is too large (0,0MB). Maximum allowed size is 0,0MB.

## After
File 'file_teste.txt' is too large (4 KB). Maximum allowed size is 1 KB.

### CODE REVIEW

File: tools/git/pre-commit [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#!/bin/sh
+git checkout main#!/bin/sh
```
Comment (haiphucnguyen) [inline tools/git/pre-commit]: Is redudant text?

File: desktop-shared/src/main/kotlin/io/askimo/ui/util/ErrorHandler.kt [hunk 2]
```diff
@@ -31,6 +32,11 @@ object ErrorHandler {
 
         // Return user-friendly message based on exception type
         return when (exception) {
+            is FileSizeExceededException -> {
+                val fileSizeStr = if (exception.fileSize >= 1_048_576) "${String.format("%.1f", exception.fileSize / 1_048_576.0)} MB" else "${exception.fileSize / 1024} KB"
```
Comment (haiphucnguyen) [inline desktop-shared/src/main/kotlin/io/askimo/ui/util/ErrorHandler.kt]: We should have a common method for this logic 

      val fileSizeStr = if (exception.fileSize >= 1_048_576) "${String.format("%.1f", exception.fileSize / 1_048_576.0)} MB" else "${exception.fileSize / 1024} KB"
                val maxSizeStr = if (exception.maxAllowedSize >= 1_048_576) "${String.format("%.1f", exception.maxAllowedSize / 1_048_576.0)} MB" else "${exception.maxAllowedSize / 1024} KB"
                "File is too large ($fileSizeStr). Maximum allowed size is $maxSizeStr."

since it is the same with one in the class ChatInputField?

File: desktop-shared/src/main/kotlin/io/askimo/ui/util/ErrorHandler.kt [hunk 3]
```diff
@@ -66,6 +72,11 @@ object ErrorHandler {
 
         // Try to get a specific message first
         val specificMessage = when (exception) {
+            is FileSizeExceededException -> {
+                val fileSizeStr = if (exception.fileSize >= 1_048_576) "${String.format("%.1f", exception.fileSize / 1_048_576.0)} MB" else "${exception.fileSize / 1024} KB"
```
Comment (haiphucnguyen) [inline desktop-shared/src/main/kotlin/io/askimo/ui/util/ErrorHandler.kt]: sane like above, a common method convert to proper MB or Kb is helpful

**Review by haiphucnguyen — COMMENTED** [review]
Hi @miguel-baptista07 , thanks for your PR. 

I left some minor comments, and you could resolve the conflict of ChatSessionService then this PR is good to go

**Review by haiphucnguyen — COMMENTED** [review]
Thanks @miguel-baptista07 for your contribution, I left some minor comments.

Also you should resolve the conflict of ChatSessionService, then this PR is good to go

**Comment by haiphucnguyen** [comment]
Screenshot 2026-04-08 at 8 56 09 AM

Also could you sign this CLA for once time. Thanks

**Comment by miguel-baptista07** [comment]
image

done!

**Comment by miguel-baptista07** [comment]
Hi @haiphucnguyen, addressed all comments:
- Removed redundant text from tools/git/pre-commit
- Extracted KB/MB conversion into the existing formatFileSize utility method
- Resolved the ChatSessionService conflict by removing unused import

Ready for review! 🙏

**Comment by haiphucnguyen** [comment]
Thank you @miguel-baptista07 ! Looking forward to your new contributions!
